# Generated by Django 3.2.18 on 2023-03-06 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booking_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
