# Generated by Django 3.2.18 on 2023-03-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_booking_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[(0, 'PLACED'), (1, 'INPROGRESS'), (2, 'READY'), (3, 'COMPLETED')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'DELETED'), (1, 'ACTIVE'), (2, 'INACTIVE'), (3, 'BLOCKED')], default=1, max_length=1),
        ),
    ]
