# Generated by Django 3.2.18 on 2023-03-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20230306_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='advance_payment',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='remaining_balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
